### ISSUE TITLE
Please mention me in the readme

### ISSUE THREAD

**Issue by mallowigi** [jsonjuri/php-syntax-color-highlighter#1]
Hi man, I know that you're using my code, it's fine, but the least you can do is to mention my name in the acknowledgements.

Thanks

**Comment by jsonjuri** [comment]
Hi, Sure no problem I will add it, sorry about that!

I also made one for HTML colors but can't get it working. If you're
interested maybe you can take a look at it?

Op di 7 jan. 2020 9:26 p.m. schreef Elior Boukhobza <
notifications@github.com>:
